import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum VotesType {
    ANSWER = "answer",
    QUESTION = "question"
}

export enum VotesVoteStatus {
    UPVOTED = "upvoted",
    DOWNVOTED = "downvoted"
}

export enum CommentsType {
    ANSWER = "answer",
    QUESTION = "question"
}

export type Answers = Models.Row & {
    content: string;
    authorId: string;
    questionId: string;
}

export type Questions = Models.Row & {
    title: string;
    content: string;
    authorId: string;
    tags: string[];
    attachmentId: string | null;
}

export type Votes = Models.Row & {
    type: VotesType;
    typeId: string;
    votedById: string;
    voteStatus: VotesVoteStatus;
}

export type Comments = Models.Row & {
    type: CommentsType;
    content: string;
    typeId: string;
    authorId: string;
}
